# Frame id for the output laserscan.
output_frame_id: camera_depth_frame
# Output topic name
topic_name: realsense_1
# Minimum sensor range (m).
range_min: 0.4
# Maximum sensor range (m).
range_max: 10.0
# Height of used part of depth img (px).
scan_height: 480
# Row step in depth image processing (px).
depth_img_row_step: 1
# If continously camera data update.
cam_model_update: false

# Height of sensor optical center mount (m).
sensor_mount_height: 0.36
# Sensor tilt angle compensation.
sensor_tilt_angle: 15.0
# Remove ground from scan.
ground_remove_en: true
# Ground margin (m).
ground_margin: 0.01
# Sensor tilt angle compensation.
tilt_compensation_en: true

